language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: 3j3JiEJ6MGZd0ZcmRKySP4/Aj0PLBCMRRK+qhcd3qfeuGaQ9pf2oEnyZ7QkUTxKY1UhV9cTTHu64IHaINOzJ+H3uKBfEL9MdSZWn2G/2LN6bmQMMCue2AKX67SsQwzB2GPPCpPn2QoL3WjjOC08kfNbrUfIDDUYHFCzGC4ToHp97kkunjRNgBZcnLLXYUtYSnPCz/JBkwgDg7FB8X8/ob7sPMRJDJ+E3cX509VrXaPLbgG9gBocaHj2g2T4v/ChG/RJYF/tCndmm9Szz5ALnRh1u2VURs3Su21nsqvwCscKnBmCmO3o46j43izc3t2GD2QfyOsryuNS9ah0kmJ+hIdbQ6zUrOEuzqqYm/B/hRSk4xXTDRZf/G5G5Hp6EsBpVlyqDjGu7tVRDSDj3x2Obs70RrIp4T983poOL777/nIPMB2nUL0uHpf23F9AE5nb7O8RzJL/fDg4ZPQGEgoX9zxFcyNjXYxuO8CD+ITgXhYcar19ikR8eCF+C77hIUtU/xM49QqlpWGbp33L0u3NdS/ipuVqApEjpnjlXay8RjLB+AqnU/b/D0UPlXky7bdGrmOryAvo+F97MoZrnM/dnKsbimtIKivEd2nT38mtvFhXxynjhz0g8I7REMAgrMDSMIIorVgKfIbeuOfH/+46d3zjmXPNH4kmn32lFqPfCxfA=
  on:
    tags: true
    repo: ricky-lim/calh
    python: 3.7
