language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rl1m
  password:
    secure: xIfvrfb9x2Rz6vSh8OCZDzPtTXAtJWYp9JsEKozcLTPYYfQJuK9DYy+9etuGdn/2i1kjx4SQMRFu4nA3v/h0Xl64LTDSGfz8s6wufKI8moPdwtL55QX3AkpPdnhDwLNWV077eKTkMFe2Ni48hXG+Y7a4wxbwQr7KgQP/SrA6mru9YNIPnaFOOKPEcyJrIMZYjeMGBaUnJhNUJOmsEFLV9GUSpHfPmlaIsqJA+itlCOyWadkknkD2BTR53H1qzi0QRIKlzGrPXHvy3nc2oLqt5QZ4nuu3I8lHpBnbgnkREQQVatmYDUYhbKols8cF6t/r6X/87NmkZnnC82ww/HpzBAZXzK4o8JnEJJKK5SU9ebcvzamrdRAZo7j0tB0jnHGN0yRn88jq+CufH06l/SQQcVNy9GJ6gWw7pUqL2znDk4j561zxkJ/LEq0iXdmmruiHEe5SUYHPvKUzf5dv9uXcVnHG4+md/m/rOtywNUUW9HxxAGpl9j5oVBnYU6n+AIUKGR9u6hQe2fxzOEetcAQYDWNXCO2kp+yDAyB5f7zE1+urXWHyYCRIksfEUqU3KFYGyJ7jdFNZiwMTgzXyD/RFSknGvQLinjOHb4Ik/SJZCYut+/QttHL19v7CbWtlwialPLVbMYIZcjEww8s2ayrtJCMqScfmZ/f4X1/8fokNd9E=
  on:
    tags: true
    repo: ricky-lim/calh
    python: 3.8
